### ISSUE TITLE
Cannot access EHCache using @Named

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-cache#72]
Hi 

Using this code I can access Cache but it's Caffeine and not EHCache as it need to be present in the application.yml to choose the impl

```java
@Factory
class CacheFactory {

    @Singleton
    @Named('refs-cache')
    Cache<String, GeneratedMessageV3> referenceCache(CacheManager manager) {
        manager.createCache('refs-cache',
                CacheConfigurationBuilder.newCacheConfigurationBuilder(String, GeneratedMessageV3,
                        ResourcePoolsBuilder.newResourcePoolsBuilder().heap(512, MemoryUnit.MB))
                //.withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofSeconds(60))
        )
    }

    @Singleton
    @Named('individuals-cache')
    Cache<String, GeneratedMessageV3> individualsCache(CacheManager manager) {
        manager.createCache('individuals-cache',
                CacheConfigurationBuilder.newCacheConfigurationBuilder(String, GeneratedMessageV3,
                        ResourcePoolsBuilder.newResourcePoolsBuilder().heap(200))
                //.withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofSeconds(60))
        )
    }
}
```

Replacing the code with 

```yaml
micronaut:
  application:
    name: my app
ehcache:
  caches:
    refs-cache:
      heap:
        max-size: 500Mb
    individuals-cache:
      heap:
        max-size: 500Mb
```

lead to  `No bean of type [org.ehcache.Cache] exists for the given qualifier: @Named('refs-cache')`

How can I access EhCache configurated in application.yml using `@Named` ?

Thank you !
